### ISSUE TITLE
Blocks can be dragged to other builders, 'max' setting not respected

### ISSUE THREAD

**Issue by bertwillekens** [TimOetting/kirby-builder#102]
When I create multiple builder fields, I can drag blocks from one builder field to another.
Not sure if this is expected behaviour, but this introduces a few issues:

- I can have more blocks than the 'max' setting by dragging them from another builder field
- I can only drag a block into an other builder field, if that builder field already contains blocks
- I can drag a block into a builder that does not comply with that builder's fieldset structure. This will result in the builder field's data being cleared when saving.

Blueprint snippet with the two fields:
```
  highlight_image:
    label: Home slider image
    help: Will be used on the home page if featured. Leave empty to use the project thumbnail instead.
    type: builder
    columns: 2
    max: 1
    fieldsets:
      image:
        label: Image
        fields:
          image:
            label: Image
            type: files
            layout: cards
            size: small
            multiple: false
            query: page.images
      video:
        label: Video
        fields:
          jwplayer_video_id:
            label: JWPlayer Video ID
            type: jwplayervideo
  highlight_image_mobile:
    label: Home slider image (mobile)
    help: Will be used to replace the <code>Home slider image</code> on mobile.
    type: builder
    columns: 2
    max: 1
    fieldsets:
      image:
        label: Image
        fields:
          image:
            label: Image
            type: files
            layout: cards
            size: small
            multiple: false
            query: page.images
      video:
        label: Video
        fields:
          jwplayer_video_id:
            label: JWPlayer Video ID
            type: jwplayervideo
```
![UJfzzNH2dB](https://user-images.githubusercontent.com/4431631/54431629-832df780-4759-11e9-988c-05fa81f137c9.gif)
