### ISSUE TITLE
Textarea icons missing inside Kirby-Builder

### ISSUE THREAD

**Issue by jensfranke** [TimOetting/kirby-builder#107]
Field-Definition:
```
label: Text
type: textarea
buttons:
  - link
  - email
```

Page-Definiton:
```
fields:
  text:
    extends: fields/textarea
  modules:
    label: Builder
    type: builder
    fieldsets:
      sectiontext:
        fields:
          text:
            extends: fields/textarea
```

Inside the Pagebuilder one icon is missing:

<img width="827" alt="Bildschirmfoto 2019-03-24 um 09 23 36" src="https://user-images.githubusercontent.com/595504/54876828-b71eb200-4e16-11e9-9e9d-8a11db5f727c.png">
