### ISSUE TITLE
File selection in textareas (via toolbar)

### ISSUE THREAD

**Issue by nilshoerrmann** [TimOetting/kirby-builder#110]
We are using a textarea inside the builder and would like to select images via the toolbar, see https://getkirby.com/docs/reference/panel/fields/textarea#file-upload-and-select. This results in the following error:

![Bildschirmfoto am 2019-04-05 um 13 16 07](https://user-images.githubusercontent.com/25466/55624896-91df5b80-57a7-11e9-8f9d-39d3c8e3e260.png)

Here is a reduced version of our blueprint:

```
interview:
  type: builder
  label: Interview
  fieldsets:
    questionset:
      label: Frage
      fields:
        question:
          type: textarea
          label: Frage
          files: page.images
``` 

My guess is that the context `page.images` is wrong given the nested structure:
How do we have to define the `files` options to enable image selection?
