### ISSUE TITLE
Pages field does not work inside a builder

### ISSUE THREAD

**Issue by SkidX** [TimOetting/kirby-builder#112]
Hi,
I've just found out that the pages field seems to not work when it is inside a builder fieldset.
When you try to select a page it raises this error: 
**Call to a member function pattern() on null**

Here is an example of blueprint:

```
fields:
    link:
        type: pages
        label: Link
        multiple: false
    main:
        type: builder
        label: Main Menu
        fieldsets:
            pageLink:
                label: Page Link
                fields:
                    text:
                        type: text
                        label: Label
                        width: 1/2
                    link:
                        type: pages
                        label: Link
                        multiple: false
                        width: 1/2
```
The first pages field outside the builder works correctly, the second one inside the builder does not work, raising that error I mentioned.

I'm using Kirby 3.1.2 and builder 2.0.7.
