### ISSUE TITLE
Unset parts of extended blueprints

### ISSUE THREAD

**Issue by tideg** [TimOetting/kirby-builder#123]
The option to unset parts of extended blueprints which came with 3.2.0-rc.1 does not work and produces the error »array_merge(): Argument #2 is not an array«.

**Example configuration from [release-description](https://github.com/getkirby/kirby/releases)**
```
# /site/blueprints/tabs/seo.yml

label: SEO
icon: search
fields:
  seoTitle:
    label: SEO Title
    type: text
  seoDescription:
    label: SEO Description
    type: text
```
Inside the requiering blueprint:

```
tabs:
  seo: 
    extends: tabs/seo
    fields:
      seoDescription: false
```

**Comment by mrflix** [comment]
Hey @tideg. Did you think about implementing this functionality yourself and creating a pull request? It might be a good start to get into plugin development yourself.

**Comment by tideg** [comment]
I´d love to @mrflix and at least I tried for two hours but I have to admit that this one is propably to advanced for me.

**Comment by findthebug** [comment]
I have a similar issue with import fields from a external file.

Kirby: 3.2.3
Builder: 2.0.13

Working example (field inline):
```yml
name: Filter Modul
label: Filter Modul
fields:
  categories:
    label: Produkt Kategorien
    type: multiselect
    width: 1/1
    options:
      red: Rot
      green: Grün
      blue: Blau
      orange: Orange

```

Failed example (import external field from yml)
```yml
name: Filter Modul
label: Filter Modul
fields:
  categories: globals/categories
```

Import def (/blueprints/globals/categories.yml)

```yml
label: Produkt Kategorien
type: multiselect
width: 1/2
options:
  red: Rot
  green: Grün
  blue: Blau
  orange: Orange
```

The import works as expected if i use it direct in a template, but inside builder it fails.
