### ISSUE TITLE
Error after updating to version 2.0.12 (array_merge)

### ISSUE THREAD

**Issue by viniciuskneves** [TimOetting/kirby-builder#127]
I'm getting the following error after updating to version 2.0.12.

![image](https://user-images.githubusercontent.com/1734873/61790976-ea9b3880-ae18-11e9-8ca4-0faebc0810f7.png)

This is my current blueprint:

```yml
type: builder
label: Hero Area
max: 1 # Optional. Limits the number of builder blocks that can be added.
fieldsets:
  marketing:
    label: Hero Marketing
    extends: heros/marketing
  primary:
    label: Hero Primary
    extends: heros/primary
  secondary:
    label: Hero Secondary
    extends: heros/secondary
  filters:
    label: Hero Filters
    extends: heros/filters
```

I'm quite new to Kirby so if you need more info let me know. I tried to debug it but couldn't get that deep.

**Comment by thin-k-design** [comment]
I have the same issue after updating, had to change to 2.0.11

**Comment by viniciuskneves** [comment]
@TimOetting do you have any input here or hints on how to solve it? Would like to help in this issue if possible.

**Comment by PaulMorel** [comment]
I get the same error when I have a field called `name` inside of a fieldset.
Example
```yml
name:
  label: Name
  type: text
  width: 1/3
```
This causes an `array_merge(): Argument #2 is not an array`. I think it interferes with the plugin.

If I change to anything else like:

```yml
fullName:
  label: Name
  type: text
  width: 1/3
```
For me, it works.

Hope this works out for you.

**Comment by TimOetting** [comment]
@viniciuskneves can you tell me if you also have a field called `name` in one of the extended blueprints?

**Comment by viniciuskneves** [comment]
> @viniciuskneves can you tell me if you also have a field called `name` in one of the extended blueprints?

No, I don't have another field called `name` in this case 😞

**Comment by thin-k-design** [comment]
> @viniciuskneves can you tell me if you also have a field called `name` in one of the extended blueprints?

I also don't have such a field...

**Comment by PaulMorel** [comment]
Could you post your full blueprints including the extended fields? There
might me some more reserved words we can't use.

**Comment by viniciuskneves** [comment]
Ok, let's go blueprint by blueprint, from innermost blueprint to the top:

`multi_components/hero.yml`
```yml
type: builder
label: Hero Area
max: 1 # Optional. Limits the number of builder blocks that can be added.
fieldsets:
  marketing:
    label: Hero Marketing
    extends: heros/marketing
  primary:
    label: Hero Primary
    extends: heros/primary
  secondary:
    label: Hero Secondary
    extends: heros/secondary
  filters:
    label: Hero Filters
    extends: heros/filters
```

`pages/one-column-flexible.yml`
```yml
title: Flexible One-Column
num: '{{ page.date.toDate("Ymd") }}'
options:
  changeTemplate:
    - one-column-article-flexible
    - two-columns-article-flexible
    - two-columns-flexible
    - one-column-flexible
    - marketing-root

tabs:
  page_options: sections/page_options

  hero: 
    label: Hero Area
    type: fields
    fields:
      hero: multi_components/hero

  content:
    label: Sections
    type: fields
    fields:
      page_sections: flexible/one_column

  seo_options: sections/seo_options
```

Annnd while doing this check, I realized that `sections/seo_options` has the following piece:
```yml
...
fields:
  ...
  custom_meta:
    label: Custom meta tags
    type: structure
    style: table
    width: 1/2
    fields:
      name:
        label: Name
        type: text
        required: true
      content:
        label: Content
        type: textarea
        buttons: false
        icon: font
        required: true
```

Which means that in another blueprint I have the `name` field but I don't think it might impact another blueprint.

Does it help somehow?
