### ISSUE TITLE
Structure field not working

### ISSUE THREAD

**Issue by guidoferreyra** [TimOetting/kirby-builder#128]
Hi! when I try to use a structure field inside the builder it fails while saving. It returns `e is null`.
Any ideas?

**Comment by findthebug** [comment]
kind of same here. if i setup a blueprint which includes a structured field, an error occurs in the backend. testet with latest version. in the first version this worked fine.
 
<img width="857" alt="Bildschirmfoto 2019-08-06 um 15 11 13" src="https://user-images.githubusercontent.com/5121132/62542642-7e7af480-b85c-11e9-9fe5-bfa6e50539db.png">

**heres the blueprint:**
label: Link Module
fields:
  linklist:
    label: Link Auflistung
    type: structure
    fields:
      name:
        label: Link Beschreibung
        type: text
        width: 1/2
      link:
        label: Link
        type: url
        width: 1/2

**Comment by TimOetting** [comment]
Hey @guidoferreyra . Does your problem still exist? Can you post the blueprint for your usecase? I checked to have a structure field inside the builder and it worked in my case

**Comment by guidoferreyra** [comment]
Hi, maybe I’m doing something wrong?

this is my blueprint:
```
footerColumns:
    type: structure
    fields:
       column:
           type: builder
           fieldsets:
               columns: blocks/columns
```

**Comment by luxlogica** [comment]
@guidoferreyra I'm a bit confused: you said you wanted to use a "structure field inside the builder", but your blueprint above seems to show that you're actually doing the opposite: putting a *builder inside a structure*. Would you be able to confirm?

Just in case, I have tested BOTH, with Kirby 3.3 and the latest Builder:
* **Structure Field inside Builder Field** works as expected, as far as I can tell. 
* **Builder Field inside Structure Field** works (we can edit and save content), but there are issues related to _previewing_ the content of the builder field inside the structure (both in table and card views - i.e., not sure exactly _what_ should be previewed in table view, and the usual builder preview tab does not seem to work inside the structure field).

You can test this by setting up a new 'plainkit' installation of Kirby, installing the Builder field plugin, and then putting this in your `site/blueprints/home.yml` blueprint:

``` yml
title: Home Page
sections:
  content:
    type: fields
    fields:
      struct_in_builder:
        type: builder
        label: Structure in Builder
        fieldsets:
          struct:
            name: Structure
            fields:
              addresses:
                type: structure
                fields:
                  street:
                    label: Street
                    type: text
                  zip:
                    label: ZIP
                    type: text
                  city:
                    label: City
                    type: text
      builder_in_struct:
        type: structure
        label: Builder in Structure
        fields:
          quotes:
            type: builder
            fieldsets:
              quote:
                name: Quote
                label: Quote by {{citation}}
                preview:
                  snippet: blocks/quote
                  css: /assets/css/blocks/quote.css
                defaultView: preview
                fields:
                  text:
                    label: Quote Text
                    type: textarea
                  citation:
                    label: Citation
                    type: text
```

@TimOetting we should probably either:
1. close this issue - as there does not seem to be a problem with structure fields inside the builder, or
2. change the title - to something like 'Preview Issues with Builder inside Structure field'. 

But TBH, I'd be inclined to close it, as the use-case of someone wanting to have a builder field inside a structure field seems extremely rare. And even in this case, this issue would be more related to the Structure field than to the Builder field itself.
