### ISSUE TITLE
default content of a structure field

### ISSUE THREAD

**Issue by grommas** [TimOetting/kirby-builder#137]
Hey, thank you for your great work! I am currently testing your plugin, but predefined content for a structure field is not showing up. Everything works as aspected outside your field. Here is a test case:
```yaml
columns:
  - width: 2/4
    sections:
      fields:
        type: fields
        fields:
          builder:
            label: Content
            type: builder
            fieldsets:
              relevant:
                name: List
                label: List
                fields:
                  relevantStructureField:
                    type: structure
                    fields:
                      testHeadline:
                        type: text
                        label: Headline
                      testContent:
                        type: text
                        label: Content
                    default:
                      - 
                        testHeadline: Test Title 1
                        testContent: Test Content 1
                      - 
                        testHeadline: Test Headline 2
                        testContent: Test Content 2
```
