### ISSUE TITLE
required hint is missing

### ISSUE THREAD

**Issue by grommas** [TimOetting/kirby-builder#138]
If the builder field itself is required, there is no asterisk showing up to inform the user.
```yaml
  - width: 2/4
    sections:
      fields:
        type: fields
        fields:
          builder:
            label: Content
            type: builder
            required: true  # relevant
```
