### ISSUE TITLE
How to display files in fieldsets?

### ISSUE THREAD

**Issue by andreasotto** [TimOetting/kirby-builder#144]
Kiry 3.3 and the following blueprint:

```
name: Text
label: Text
fields:
    textitems:
        type: builder
        label: Einträge
        columns: 2
        fieldsets:
            text:
                name: Text
                label: Text
                fields:
                    text:
                        label: Text
                        type: textarea

            image:
                name: Bild
                label: Bild
                fields:
                    image:
                        label: Bild
                        type: files
```

I don't get the output in the template. I tried with this:

```
    <?php foreach($section->textitems()->toBuilderBlocks() as $item) : ?>
      ...
    <?php endif ?>
```

Trying to get the image from `$item`, but how ..?
