### ISSUE TITLE
Bug: required attribute ignored

### ISSUE THREAD

**Issue by andreasotto** [TimOetting/kirby-builder#146]
blueprint:

```
                            imgtoggle:
                                label: Bild oder Icon
                                type: select
                                default: icon
                                required: true
                                options:
                                    icon: Icon
                                    img: Bild
```

The `required`-Attribute is ignored. The `select`-Field isn't mandatory although `required` is `true`.
