### ISSUE TITLE
translate: false for builder field?

### ISSUE THREAD

**Issue by alancwoo** [TimOetting/kirby-builder#152]
Is there any way to prevent translation of a builder field? Applying `translate: false` to the field doesn't seem to have any effect:

example.yml
```
label: Example
type: builder
translate: false
fieldsets:
  ...
```

**Comment by piaaaac** [comment]
Similar but slightly different issue: fields inside a builder field with `translate: false` don't seem to get the default language's value. Or better, they do in the panel but don't pass the value to the `$page` object in the template. Is this intended or for any reason? Hope I'm not missing something.

```
  mybuilder:
    label: Page Builder
    type: builder
    fieldsets:

      twocols:
        name: Two columns block
        preview: 
          snippet: blocks/twocols
          css: levignedisilvia-2/assets/css/panel.css
        defaultView: preview
        fields:
          text:
            label: Text
            type: textarea
          images:
            label: Images
            type: files
            translate: false # this field
```

**Comment by caplod** [comment]
I have the exact same Problem:
the images are set to null in the english translations

how can I fix this?
```
name: Text (mit Bild)
tabs:
  ...
  imagetab:
    label: Bild
    fields:
      image:
        label: Bild
        type: files
        max: 1
        layout: cards
        translate: false # this field looks ok in backend (not editable)
```
