### ISSUE TITLE
File template not respected in files field

### ISSUE THREAD

**Issue by olivertedwards** [TimOetting/kirby-builder#155]
Thank you for your amazing efforts with the plugin!

I have an image block with a files field used to select an image from uploads. On my page blueprint, there are two files fields to separate blueprints for images and files.

When I click to select an image in the builder block, I expect that the popover dialog queries only uploads with template: image.

However, the template setting isn't respected in the popover dialog and shows all images and files in the page.

Trying searching for similar issues, but didn't find anything. Any thoughts? 🧦🧤

```yaml
builder:
  type: builder
  fieldsets:
    image:
      tabs:
        content:
          fields:
            images:
              type: files
              multiple: false
              template: image
              uploads: false
...
```
