### ISSUE TITLE
Fetch with Axios

### ISSUE THREAD

**Issue by KPLehmann** [TimOetting/kirby-builder#157]
Hi! 
The Builder works great in Kirby, but @TimOetting can you give me an example how I can implement it with vuex / axios?

Kind of example i'm looking for:
```
"mybuilder": {
      "query": "page.mybuilder.toBuilderBlocks",
      "select": {
             "text": "text"
            }
       },
```

Setup of by Blueprint: 
```
    fields:
      mybuilder:
        label: Project Content
        type: builder
        fieldsets:
          text:
            label: Text
            fields: 
              text:
                label: Project Text
                type: textarea
          gallery:
            label: Gallery
            fields:
              gallery:
                label: Gallery
                type: files
                template: image
```
Any help is much appreciated…
