### ISSUE TITLE
Nesteds builder not working

### ISSUE THREAD

**Issue by isUnknown** [TimOetting/kirby-builder#176]
Nested builders doesn't seem to work for my part. The panel display a blank add modal :

<img width="1426" alt="Capture d’écran 2020-08-13 à 09 54 02" src="https://user-images.githubusercontent.com/61452348/90108691-fa026200-dd4a-11ea-916a-ae3a425ac8ce.png">

The console throws two errors :

```
Object { status: "error", message: "Le blueprint «&nbsp;Sous-partie&nbsp;» n’a pu être chargé", code: 404, exception: "Kirby\\Exception\\NotFoundException", key: "error.blueprint.notFound", file: "/kirby/src/Cms/Blueprint.php", line: 291, details: [], route: "kirby-builder/pages/(.*)/builderconfig" }
app.js:1:33497
```  
```
Uncaught (in promise) 
Object { status: "error", message: "Le blueprint «&nbsp;Sous-partie&nbsp;» n’a pu être chargé", code: 404, exception: "Kirby\\Exception\\NotFoundException", key: "error.blueprint.notFound", file: "/kirby/src/Cms/Blueprint.php", line: 291, details: [], route: "kirby-builder/pages/(.*)/builderconfig" }
```

The french's message says "The blueprint couldn't be loaded".

Here is my blueprint, in case I missed something :

```
title: Linéaire

sections:
  builder:
    type: fields
    fields:
      lineaire:
        type: builder
        fieldsets:
          slide:
            name: Slide basique
            fields:
              title:
                label: Titre
                type: text
              text:
                label: Texte
                type: markdown
          part:
            name: Partie
            fields:
              title:
                label: Titre
                type: text
              subpart:
                type: builder
                fieldsets:
                  name: Sous-partie
                  fields:
                    textsubpart:
                      label: Texte
                      type: markdown
```

**Comment by owzim** [comment]
@isUnknown `fieldsets` needs to be an object containing the blocks:

Tested and working:

```yaml
title: Linéaire

sections:
  builder:
    type: fields
    fields:
      lineaire:
        type: builder
        fieldsets:
          slide:
            name: Slide basique
            fields:
              title:
                label: Titre
                type: text
              text:
                label: Texte
                type: markdown
          part:
            name: Partie
            fields:
              title:
                label: Titre
                type: text
              subpart:
                type: builder
                fieldsets:
                  souspartie:
                    name: Sous-partie
                    fields:
                      textsubpart:
                        label: Texte
                        type: markdown
```

I changed `part.fields.subpart.fieldsets.fields` to `part.fields.subpart.fieldsets.sourpartie.fields` (I added `sourpartie` right between `fieldsets` and `fields`.

I feel you. this nesting stuff and kirby's blueprints in general can get confusing at a certain complexity level.
