### ISSUE TITLE
Impossible save required field

### ISSUE THREAD

**Issue by illycz** [TimOetting/kirby-builder#179]
Kirby Builder 2.0.15
Kirby 3.4.3

Plainkit installation within simple blueprint:
```
title: Default Page
preset: page
fields:
  text:
    label: Text
    type: textarea
    size: large
  mybuilder:
    label: Page Builder
    type: builder
    fieldsets:
      quote:
        label: Quote
        fields:
          citation:
            label: Citation
            type: text
            required: true
```

I can't save page with populated field:
![image](https://user-images.githubusercontent.com/2109984/93920180-195bba00-fd0f-11ea-8db7-a3242833c906.png)

Error form console:
![image](https://user-images.githubusercontent.com/2109984/93920229-2d072080-fd0f-11ea-8154-acb147d9532d.png)

Any suggestion?
My client can't update pages within Kirby builder.

Thanks!
