### ISSUE TITLE
Imported fonts in CSS aren't loaded

### ISSUE THREAD

**Issue by RustyDev** [TimOetting/kirby-builder#181]
I'm loading my main css file so the previews are consistent with the site styles. 

```yaml
name: Testimonials
label: Testimonials
preview:
  snippet: blocks/testimonials
  css: /assets/css/style.css
```

In style.css I'm loading a few google fonts:

```css
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,300&family=Playfair+Display:wght@700&display=swap");
```

The fonts show correctly on the site, but the preview will not load them.
