### ISSUE TITLE
extends: sections/something not working correctly ?

### ISSUE THREAD

**Issue by ivandaum** [TimOetting/kirby-builder#185]
Hello everyone,

New to kirby here, I'm trying to extends a "news" section blueprint. The interface works, but instead of showing the "new Post" modal, it show a list of my site's pages.

So here's my agencies.yml
```
sections:
  main:
    type: fields
    fields:
      agencies:
        type: builder
        columns: 2
        max: 2
        label: Agencies
        fieldsets:
          agency:
            name: Agency
            fields:
              partners:
                extends: sections/news
```

And the sections/news
```
type: pages
headline: Post
parent: kirby.page('agencies')
template: new
image:
  query: page.images.template("cover").first
  ratio: 3/2
  cover: true
```

My `sections/news` is working on `site.yml` thought.

Am I missing something here ?
