### ISSUE TITLE
Images in nested builder fields disappear, when other fields change

### ISSUE THREAD

**Issue by owzim** [TimOetting/kirby-builder#187]
Thanks for a truely awesome kirby field!

* Kirby version: `3.4.4`
* Builder version: `2.0.16`
* Tested in latest **Firefox** and **Chromium**

Drop-in testing page blueprint:

```yaml
title: Builder Image Test
preset: page
fields:
  blocks:
    label: Blocks
    type: builder
    fieldsets:
      builderimagetest:
        name: Builder Image Test
        label: Builder Image Test
        preview: false
        fields:
          align:
            label: Align
            type: select
            options:
              left: Left
              center: Center
          items:
            label: Items
            type: builder
            fieldsets:
              item:
                name: Item
                label: Item
                fields:
                  image:
                    label: Image
                    type: files
                    multiple: false
                    layout: list
                    size: small
```

Images in nested builder fields disappear, when other fields change. Not only visually but the value is empty, so on save, image references get deleted :(

This first happens **after first save and reload** and then persists.

Screen recording of what is happening:

![builder-image-test-01](https://user-images.githubusercontent.com/1720088/99685138-888d2a80-2a82-11eb-8d62-30b3022e0820.gif)

Any field changes in the form make all nested images disappear.

![builder-image-test-02](https://user-images.githubusercontent.com/1720088/99685297-ba05f600-2a82-11eb-97d3-58ee22663062.gif)
