### ISSUE TITLE
Impossible to save required fields for Structures in Builder

### ISSUE THREAD

**Issue by felipep** [TimOetting/kirby-builder#189]
For a structure inside the builder like:

````
fields:
    slider_items:
        type: structure
        label: Slide Elemente
        fields:
            picture:
                label: Bild
                extends: fields/image
                max: 1
                required: true
````

The problem of https://github.com/TimOetting/kirby-builder/issues/179 still exists
