### ISSUE TITLE
3.6 compatibility?

### ISSUE THREAD

**Issue by foxacid** [TimOetting/kirby-builder#198]
I understand that by and large this fantastic plugin has been superseded by the native Kirby blocks.

However, I have some older projects that rely on kirby-builder and it seems that upgrading them to 3.6 breaks the plugin.

I tested this on a starterkit with the following blueprint fields:

```
builder:
  type: builder
  fieldsets:
    image:
      fields:
        picture:
          type: files
          layout: cards
          max: 1
    quote:
      fields:
        text:
          type: textarea
```

This is what happens:

https://user-images.githubusercontent.com/12812201/151938385-9ea44bbc-4845-4737-a278-a66c2b484ee0.mov

FWIW there are no errors in the console.

Will there eventually be a fix for this or should I migrate the site to Kirby blocks? ]

Many thanks!
