### ISSUE TITLE
Structure field in the Kirby-builder

### ISSUE THREAD

**Issue by vauvarin** [TimOetting/kirby-builder#22]
Hi,

I tried to add a "structure field" in the kirby-builder. I can see it in the Panel but the "Add" button is not available and I can't add multiple entries.

This is my blueprint:

```
title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  builder:
    label: Sections
    type: builder
    modalsize: extralarge
    fieldsets:
      addresses:
        label: Addresses
        type: structure
        modalsize: large
        entry: >
          {{street}}<br />
          {{zip}} {{city}}
        fields:
          street:
            label: Street
            type: text
          zip:
            label: ZIP
            type: text
          city:
            label: City
            type: textarea
```

See the attached screenshot
![kirby_builder_structure_field](https://cloud.githubusercontent.com/assets/664089/16358645/1b1cae1e-3b1a-11e6-932c-2b58f9b4c8d3.png)
