### ISSUE TITLE
Required fields & validation not behaving as expected

### ISSUE THREAD

**Issue by good-idea** [TimOetting/kirby-builder#24]
It seems that if a required field is left blank, hitting 'OK' closes the modal without saving the information.

If there is a field that requires validation, hitting OK will result in no action, even if the value is valid - the modal stays open, and no error messages.

```
fields:
  blocks:
    label: Content
    type: builder
    fieldsets:
      chapter:
        label: Chapter Header
        fields:
          text:
            label: Text
            type: text
            required: true
        entry: >
          <h1>{{text}}</h1>
      bodytext:
        label: Text
        snippet: blocks/bodytext.panel
        fields:
          text:
            label: Text
            type: wysiwyg
          validNumber:
            label: Validation Test
            type: number
            required: true
            validate:
              between:
                - 2
                - 4

```
