### ISSUE TITLE
Sections not showing on page

### ISSUE THREAD

**Issue by victorberland** [TimOetting/kirby-builder#28]
I am facing a problem where I can't get the sections to show up on my page. They show up in the panel like they're supposed to, however nothing shows up on my page. The divs for the sections do not show up in Inspector.

Here are my files:

Blueprint for project.php:
```
<?php if(!defined('KIRBY')) exit ?>

title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  cover:
    label: Cover Image
    type: image
  line1:
    type: line
  builder:
    label: Sections
    type: builder
    fieldsets:
      texto:
        label: Text
        snippet: sections/text
        fields:
          text:
            label: Text
            type: textarea
```

Template for project.php:
```
<?php snippet('header') ?>

<div class="container">

  <main class="projectpage">

    <div class="content">

      <?php foreach($page->builder()->toStructure() as $section): ?>
        <?php echo snippet('sections/' . $section->_fieldset(), array('data' => $section)) ?>
      <?php endforeach ?>

    </div>

  </main>

</div>

<?php snippet('footer') ?>

```

Snippet text.php:
```
<div class="text">
  <?= $data->text()->kt() ?>
</div>

```

I copied the files from the ZIP in to _/site/fields/builder_.
