### ISSUE TITLE
Problem with entry field

### ISSUE THREAD

**Issue by askenielsen** [TimOetting/kirby-builder#53]
Hi

I simply can't seem to get the entry field to work:

I've been trying to use it as follows
```
imageBanner:
  label: Image Banner
  snippet: sections/imagebanner
  fields:
    picture:
      label: Background Image
      type: image
    text:
      label: Headline Text
      type: text
    entry: >
      <img src="{{_fileUrl}}{{picture}}" height=120px/></br>{{text}}
```

But i keep getting an empty module. Any ideas?
