### ISSUE TITLE
make entry option buttons smaller and floating

### ISSUE THREAD

**Issue by bnomei** [TimOetting/kirby-builder#55]
maybe you could add something like this via a plugin config setting.

![smaller](https://user-images.githubusercontent.com/3265642/33767386-a27ee9f4-dc21-11e7-9e87-f852474e21c9.png)

```css
.structure-entry.builder-entry {
    position: relative
}
.structure-entry.builder-entry .builder-entry-fieldset-name {
    right: 70px;
    line-height: 35px;
    height: 35px;
    padding: 0 1em
}
.structure-entry.builder-entry .structure-entry-options.builder-entry-options {
    position: absolute;
    top: 0;
    right: 0
}
.structure-entry.builder-entry .structure-entry-options.builder-entry-options .btn-with-icon {
    overflow: hidden;
    color: transparent;
    border-width: 0;
    padding: 0;
    width: 35px;
    height: 35px;
    background-color: rgba(0, 0, 0, .62)
}
.structure-entry.builder-entry .structure-entry-options.builder-entry-options .btn-with-icon i {
    width: inherit;
    height: inherit;
    line-height: 35px;
    font-size: 17.5px;
    padding: 0 5px;
    color: #fff
}
.structure-entry.builder-entry .structure-entry-options.builder-entry-options .btn-with-icon:hover {
    background-color: rgba(0, 0, 0, .31)
}
```
