### ISSUE TITLE
No preview in the panel.

### ISSUE THREAD

**Issue by benni-t** [TimOetting/kirby-builder#56]
Hello friends,
kirby builder works well, but i don't get a preview of the content. 

The content is saved, because I get it when i edit a modul.

Please can you help me?! 

![bildschirmfoto 2018-01-02 um 10 36 40](https://user-images.githubusercontent.com/12278134/34479843-2ed5f7d6-efa9-11e7-9218-e3e83e090fca.png)

**Comment by WeTurkstra** [comment]
Have you specified an entry, but is it empty? Or a snippet with no content?

**Comment by Galothus** [comment]
This happens when you have your **snippet defined in blueprint, but the template does not exist**.

Using default kirby-builder example 
```yaml
fields:
...
  builder:
    label: Sections
    type: builder
    fieldsets:
      bodytext:
        label: Body Text
        snippet: sections/bodytext ##check if bodytext.php exists in snippets/sections folder
        fields:
          text:
            label: text
            type: textarea
```
If you comment out like this `#snippet: sections/bodytext` , you'll most likely see your content appear in the panel.
