### ISSUE TITLE
Options will be ignored

### ISSUE THREAD

**Issue by macx** [TimOetting/kirby-builder#67]
Some field options are leading to errors (like max at the files field) or doesn't do anything (see textfield) if they're included via `extends` options.

![image](https://user-images.githubusercontent.com/84112/51474080-7e168280-1d7e-11e9-8162-bd46ba918ae8.png)

**Comment by TimOetting** [comment]
Hey @macx,

Can you post the blueprint that extends these fields? Right now, I am a little bit surprised that the group blueprint works at all :) Some betas ago, it didn't work and I didn, add support for them in the meantime. Does it work if you simply leave away the first two lines of you blueprint?

Thanks,
Tim

**Comment by macx** [comment]
@TimOetting Below is a excerpt of the blueprint I'm using. I cannot remove `type: group` and `field`, that doesn't. [The spec](https://getkirby.com/docs/guide/blueprints/extending-blueprints) is correct. What's working – until I'm using any option (like `max: 1`) to tweek it – is the following:

blueprints/blocks/cover.yml
```yaml
type: group
fields:
  image:
    label: image
    type: files
```

And the initating yaml blueprints/pages/default.yml:

```yaml
title: Default Page

tabs:
  page:
    label:
      en: Page
      de: Seite
    columns:
      - width: 2/3
        sections:

          content:
            type: fields
            fields:
              [...]

      - width: 1/3
        sections:
          meta:
            type: fields
            fields:
              [...]

          files:
            type: files

  content:
    label:
      en: Content
      de: Inhalt
    icon: text
    preset: page
    pages: false

    fields:
      bodytext:
        label: Bodytext
        type: textarea
        buttons:
          - headlines
          - bold
          - link
          - email
        size: medium

      builder:
        label:
          en: Content
          de: Inhalt
        type: builder
        columns: 1
        fieldsets:
          text:
            label: Text
            preview:
              snippet: blocks/text
            fields:
              text:
                label: Text
                type: textarea
                buttons:
                  - headlines
                  - bold
                  - link
                  - email
                size: medium
              [...]
          cover:
            label: Cover
            extends: blocks/cover
          image:
            label: Bild
            fields:
              [...]

```
