### ISSUE TITLE
Conflict with markdown plugin.

### ISSUE THREAD

**Issue by AhoyLemon** [TimOetting/kirby-builder#7]
I'm currently building a site using [Visual Markdown](http://getkirby-plugins.com/visual-markdown-editor) in some places and kirby-builder in others. However, I can't use them both simultaneously.

If I try to set any field inside any builder to `type: markdown`, the page errors out.

![image](https://cloud.githubusercontent.com/assets/3413200/11347399/e4cd8554-91e6-11e5-8d70-8e69b44f5fe4.png)

Devtools doesn't display any errors in the console, but the entries are invisible and the **Add** button is unclickable.

**Comment by Targoran** [comment]
Hm that's odd, I'm using the plugin as well with visual markdown installed and use it inside the builder structure. Since the plugin is based on the regular structure field, it should be compatible with any other fields.

Are you sure your blueprint structure is correct? Kirby tends to fail as soon as the yaml syntax is not correct, e.g. wrong indentation etc.

Here's the code from my blueprint using builder with visual mardown

```yaml
builder:
    label: Page Content
    type: builder
    fieldsets:
      headline:
        label: Headline
        fields:
          headline_text:
            label: Headline
            type: text
      columntext:
        label: Text (multi-column)
        fields:
          text:
            label: Text
            type: markdown
```
