### ISSUE TITLE
The field type "builder" does not exist

### ISSUE THREAD

**Issue by aristotheme** [TimOetting/kirby-builder#71]
It was working but I downloaded last files and it says

`The field type "builder" does not exist`

**Comment by aristotheme** [comment]
```
title: Page
preset: pages
icon: page

fields:
  builder:
    label: Page Builder
    type: builder
    columns: 1
    max: 100
    
    fieldsets:
      tx-001:
        label: Text and Button
        tabs: 
          extends: blocks/tx-001

      tx-002:
        label: Text and Button in 1/2 Column
        tabs: 
          extends: blocks/tx-002

      tx-003:
        label: Text, Button and Author in 1/2 Column
        tabs: 
          extends: blocks/tx-003
```
