### ISSUE TITLE
About File

### ISSUE THREAD

**Issue by aristotheme** [TimOetting/kirby-builder#75]
Hi Tim

```
brandLogo:
  label: Logo
  type: files
  multiple: false
  width: 1/3

brandName:
  label: Brand Name
  type: text
  width: 2/3
  icon: text
  default: Shuffle
```

How Can I use this in template?

```
if($image = $page->image($data->brandLogo()):
// do stuff and use $image in the rest of the code so as not to repeat yourself
endif;
```

I got error :(
