### ISSUE TITLE
Question / blueprint usage

### ISSUE THREAD

**Issue by mearno** [TimOetting/kirby-builder#8]
Did any of you guys or girls get builder working with blueprint snippets like Bastian whites about here https://github.com/getkirby/panel/pull/433#issuecomment-150559661

I tried but can't get it to work. For long builder yml I think this would be great.

Thanks.

**Comment by dionysiusmarquis** [comment]
Hi,
can you try tu use ``extends ``

Not working so far:
```
fieldsets:
  copy: copy
  video: video
```

should work:
```
fieldsets:
  copy: 
    extends: copy
  video: 
    extends: video
```

**Comment by mearno** [comment]
I've got it working like this:

In blueprints/fields I've got sidebar.yml with the builder yml starting with:

``` yaml
    label: Sidebar blocks
    type: builder
    fieldsets:
      textblock:
        label: Text block
        entry: > 
```

In normal blueprint files I include this with:

``` yaml
  headline:
    label: Sidebar
    type: headline
  builder: sidebar
```

(I'm using a tabs field but changed to headline for this example)

It's working great, got a nice sidebar block builder going :)
