### ISSUE TITLE
UID in page content, ok to remove?

### ISSUE THREAD

**Issue by louiswalch** [TimOetting/kirby-builder#81]
I am going to be migrating some content from another system to Kirby 3, using PHP to generate the page's .txt file. I noticed that the builder is adding a UID to each one of the sections added to a page. Is this needed? Seems to work if I remove it from the .txt file. If I can't remove it, how would I create this value programmatically as part of my migration script?

```
----

Sections: 

- 
  title: This is a text section.
  text: Foo bar.
  _key: text
  download_file: null
  _uid: text_1548707450486_1381
- 
  title: This is about section.
  text: Foo biz.
  citation_person: John Doe
  citation_title: Person
  vimeo_id: "123456"
  details_title: Some details
  details_text: Hi.
  fineprint: This is the fine print.
  download_file: [ ]
  download_preview: [ ]
  download_button: Download PDF
  sponsors: [ ]
  _key: about
  line_1: null
  line_2: null
  line_3: null
  line_4: null
  _uid: about_1548707572870_1495
```
