### ISSUE TITLE
File field lose images

### ISSUE THREAD

**Issue by mungle** [TimOetting/kirby-builder#85]
Hello!
If I add an image wit an file field and I save it, when I leave that page (on panel) and I edit it again, the file field will lose my images preview. The content still right but the preview is missed.

here my blueprint

```
  rowimage:
    label: Image - 1/1
    tabs:
      contenuto:
        label: Contenuto
        icon: edit
        fields:
          immagine:
            label: Immagine
            type: files
            multiple: false
      style:
        label: Stile
        icon: cog
        fields:
          textaligncol1:
            label: Allineamento testo
            type: select
            options:
              text-align-left: Sinistra
              text-align-center: Centro
              destra: Destra
              giustificato: Giustificato
            width: 1/3
          line:
            type: line
            width: 2/3
          rowwidth:
            label: Dimensione sezione
            type: select
            # default: small
            options:
              small: Small
              full: Fullscreen
            width: 1/3
          padding1:
            label: Spaziatura
            type: checkboxes
            default: row_padding_all
            options:
              nopadding: Nessun padding
              row_padding_top: Sopra
              row_padding_bottom: Sotto
              row_padding_right: Destra
              row_padding_left: Sinistra
            width: 1/3
```

I don't know where to look at... so I hope someone could help!
Thank you!
