### ISSUE TITLE
Default state of a toggle field

### ISSUE THREAD

**Issue by czJonny** [TimOetting/kirby-builder#88]
Hello!

When I put a toggle field inside kirby-builder block and I create a new block, the state of the field shows it is "on". However, the value that is saved inside .txt file is "false". I tried to specifically set the default state of the field to "false", but it did not help.

**Comment by bavarianbytes** [comment]
Same here

**Comment by TimOetting** [comment]
Hey @czJonny  and @bavarianbytes ,

could you please checkout the latest version? The bug should be fixed now.

**Comment by czJonny** [comment]
Yes, now it works! Thank you very much, Tim!

**Comment by bavarianbytes** [comment]
Sorry, cannot confirm it. My code:
```
img_rounded:
    label: Abgerundete Ecken
    type: toggle
    default: false
    text:
      - Nein
      - Ja
```
Tried `default: false` and `default: 'false'`. In both cases the button is shown as true. Saving is correct no matter if say true or false as default.
