### ISSUE TITLE
field groups

### ISSUE THREAD

**Issue by bavarianbytes** [TimOetting/kirby-builder#89]
Tried to use both variants of [reusable field groups](https://getkirby.com/docs/guide/blueprints/extending-blueprints#reusing-and-extending-field-groups) (via `fieldname: /path/` and via `fieldname:\n extend: /path/` ), but they do not seem to work (Error: `unknown field type "group"`). 

Are there any possibilities to reuse field groups?

**Comment by saschabregenhorn** [comment]
This doesn't answer your question, but you can organize the builder blocks in single files as well and combine them via „extends“, e.g.

`extends: blocks/preferences-textareas` 

Even works „nested“.

**Comment by bavarianbytes** [comment]
Thx! But therefore you cannot compile multiple files into one field block, can you?

**Comment by TimOetting** [comment]
@bavarianbytes good question. Did you try it? Under the hood, Kirby Builder uses a native method. I am not sure if it also works with multiple extends. Would this be possible with field groups?

**Comment by bavarianbytes** [comment]
Multiple extends are not possible (`array given, string expected`). I think it's not the concept of extends. Extending means to use a blueprint and add some stuff. I think Kirbys "field groups" are for joining fields from different sources together.

Therefore i think it would be cool if Builder would support the field type "group" (`The field type "group" does not exist`).

**Comment by mrflix** [comment]
I'm porting a builder setup from kirby v2 to kirby v3. It is a form builder and since all fields have some settings in common I grouped them:
```yml
type: group
fields:
  name:
    label: Name
    type: text
    required: true
  mandatory:
    label: Mandatory
    type: checkbox
    default: true
    text: has to be filled out
    width: 1/2
  width:
    label: Width
    type: select
    default: full
    options:
      full: Full Width
      1/2: 1/2
      1/3: 1/3
      2/3: 2/3
      1/4: 1/4
      2/4: 2/4
      3/4: 3/4
      1/5: 1/5
      2/5: 2/5
      3/5: 3/5
      4/5: 4/5
    width: 1/2
```
So I, too, had to learn that grouping is not yet supported in builder:
![The field type "group" does not exist error](https://user-images.githubusercontent.com/60777/59854556-6fef8100-9373-11e9-9b59-e9740534e10e.png)
> As I said, I will make them work for the builder field.

[Source](https://github.com/getkirby/kirby/issues/1233#issuecomment-445212150). Will you keep your pinky promise and support them in builder, Tim?
