### ISSUE TITLE
Translatable fieldset labels

### ISSUE THREAD

**Issue by medienbaecker** [TimOetting/kirby-builder#91]
This was already a problem with the Kirby 2 builder, but I guess it's a different story now.

Using translated labels for the fieldset results in this:

![image](https://user-images.githubusercontent.com/7975568/53007993-aa362980-3438-11e9-891d-a06b57ad54b3.png)

```yaml
builder:
  label: Builder
  type: builder
  fieldsets:
    input:
      label:
        de: Text field
        en: Textfeld
```
