### ISSUE TITLE
No route found for path

### ISSUE THREAD

**Issue by yordanoff** [TimOetting/kirby-builder#99]
When trying to use the `pages` type in site.yml I get the following: `No route found for path: "kirby-builder/pages/fields/widgets+menu+entries1" and request method: "GET"` (Screenshot: https://cl.ly/9d166813f351)

Also, when I click on the preview I get `Cannot read property 'replace' of undefined`.

Here is the blueprint:

```
          widgets:
            label: Footer Widgets
            type: builder
            columns: 1
            max: 10
            fieldsets:
              menu:
                label: Menu
                preview:
                  snippet: blocks/quote
                  css: /testproject/dist/styles.css
                  js: /testproject/dist/main.js
                fields:
                title:
                  label: Title
                  type: text
                  width: 1/2
                width:
                  label: Width
                  width: 1/2
                  type: select
                  default: 1-3
                  options:
                    1-1: 1/1
                    1-2: 1/2
                    1-3: 1/3
                entries:
                  label: Entries
                  type: pages
```

Any idea what is the issue?
